server:
  port: 10010
spring:
  application:
    name: mszuth-admin
  datasource:
    url: jdbc:mysql://localhost:3309/msauth?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    username: root
    password: root
    hikari:
      minimum-idle: 10
      maximum-pool-size: 20
  jpa:
    open-in-view: false # Open Session in View 保持视图层的会话，默认开启，需要将其设为false
    properties:
      hibernate:
        hbm2ddl:
          auto: update # 是否自动创建或者修改DB 生产环境关闭
    show-sql: true