server:
  port: 10014
spring:
  security:
    oauth2:
      client:
        provider:
          spring:
            issuer-uri: http://localhost:10013
        registration:
          oauth2-test:
            provider: spring
            client-id: oauth2-test
            client-secret: "123456"
            scope:
              - openid
            authorization-grant-type: authorization_code
            redirect-uri: http://127.0.0.1:10014/login/oauth2/code/oauth2-test